name: Add new issues to the project board

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.projects.createCard({
            column_id: 12055435,
            content_id: context.payload.issue.id,
            content_type: "Issue"
          });
