name: Tag releases to the main branch

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    name: Tag a new release
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - run: |
          git config --local user.email "github-action[bot]@github.com"
          git config --local user.name "GitHub Action Bot"

          TAG=`date '+%Y-%m-%d-%H.%M.%S'`

          git tag $TAG
          git push origin refs/tags/${TAG}
