---
name: Remove the 'next' label from closed issues

on:
  issues:
    closed:

jobs:
  unlabel:
    runs-on: ubuntu-latest

    steps:
      - name: Remove the 'next' label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: next
