---
name: Remove the 'next' label from closed issues

on:
  issues:
    closed:

tasks:
  unlabel:
    - name: Remove the 'next' label

      runs-on: ubuntu-latest
      
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: next
